### ISSUE TITLE
How is kubectl auth'd to push the secrets to Kubernetes

### ISSUE THREAD

**Issue by colemickens** [ployst/docker#7]
If I'm running a secured cluster, how does kubectl know how to talk to the apiserver (where it lives, client certificate, etc) in order to push secrets? 

I think this container should be getting a ServiceAccount secret during deployment and using that to talk back to the apiserver.

See: http://kubernetes.io/v1.1/docs/user-guide/accessing-the-cluster.html#accessing-the-api-from-a-pod

**Comment by alexcouper** [comment]
@colemickens 

I'm currently running this container using the default service account.
```
$ kubectl get pods/letsencrypt-rc-w8191 -o yaml
volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-w3n5y
      readOnly: true
  serviceAccount: default
  serviceAccountName: default
```
That's how it's able to create secrets, delete rcs etc.

If you want to run it under some other service account, I believe these are the steps:

1. Create a service account
2. In your RC definition of the pod, set the `spec.serviceAccount` to the name of your newly created service account (rather than using the default)

http://kubernetes.io/v1.1/docs/user-guide/service-accounts.html will help

Let me know if that helps.

**Comment by colemickens** [comment]
So when `kubectl` is called in `save_certs.sh`, does it know it automatically look for a token in `/var/run/secrets/kubernetes.io/serviceaccount` ?

**Comment by alexcouper** [comment]
@colemickens yeah this appears to be part of kubectl

https://godoc.org/k8s.io/kubernetes/pkg/kubectl/cmd/util#DefaultClientConfig

>  However, if it appears that we're running in a kubernetes cluster container environment, then run with the auth info kubernetes mounted for us. Specifically:
    
> The env vars KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT are
    set, and the file /var/run/secrets/kubernetes.io/serviceaccount/token
    exists and is not a directory.

**Comment by colemickens** [comment]
Awesome, thanks for this project and the fast support!
